### ISSUE TITLE
When creating a new office hours entry, allow user to select a quarter, then a course, then a tutor (rather than entering a tutor assignment id)

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-s21/proj-ucsb-cs-las#112]
# User Story

As a mentor, I can use a "select tutor" component to create an office hour entry, so that I don't have to look up my tutor assignment ID by hand when creating my office hours.

** NOTE: Complete Story #111 first; it involves developing a component that will be used in this story **

# Acceptance Criteria

- The user can create a new office hour entry using the new component, and it will be saved to the database properly.
- This should be a separate Javascript component, so it can be reused if necessary

# Implementation Todos

Front end:

- [ ] The "Tutor Assignment ID" text field is replaced with a "select tutor" component that allows the user to select the quarter, course, and tutor for the office hour they want to create. 
- [ ] The "quarter" drop-down is populated with all the quarters currently stored in the database
- [ ] The "courses" drop-down is populated with all of the courses in the selected quarter
- [ ] The "tutors" drop-down is populated with the names of all the tutors who are assigned to the selected course. (That is, there exists a TutorAssignment for that tutor with the selected course)

...

Back end:

- [ ] The component should be created with three props, each of which is a function that can be called to populate the drop down menus
        - [ ] The getQuarters() function doesn't need to take any params
        - [ ] The getCourses() function should take a quarter as a param
        - [ ] The getTutorAssignments() should take a course id as a param.

- [ ] There shouldn't be any need to change the way an OfficeHour object 
...

Testing:

- [ ] There is a front end test checking that the new component is present on the Office Hours create page
- [ ] All tests for creating/saving office hours still pass without modification
...

# Discussion

At the moment if you want to enter office hours for a tutor, you have to look up their "tutor assignment id number", which is pretty user unfriendly.

That is, on this screen, you are asked for a tutor assignment id:

![image](https://user-images.githubusercontent.com/1119017/108750635-1cddb200-74f6-11eb-94fb-5afbba4a935a.png)

That comes from looking it up on this screen.  For example, Jacqui for CMPSC 156 W21 is number "21"

![image](https://user-images.githubusercontent.com/1119017/108750590-10595980-74f6-11eb-91a9-0f9429670079.png)

What we want instead, is
*  a drop down menu where you can select a quarter
* once you select one, you get a drop down menu where you can select a course
* once you select one, you get a drop down menu where you can select a tutor assignment from that course. (by Name)

The component should be created with three props, each of which is a function that can be called to populate the drop down menus. The getQuarters() function doesn't need to take any params, the getCourses() function should take a quarter as a param, and the getTutorAssignments() should take a course id as a param.

**Comment by JacquelineMai** [comment]
Complete by staff pr #169, which created the component and applied it in the office hr page
