### ISSUE TITLE
F20-6pm-a public/member facing features

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-s21/proj-ucsb-cs-las#13]
In this epic, we concentrate on features available to the public (when not logged in) and to members logged in with ucsb accounts.

* Public and guest can see a list of all courses for current quarter (courses not in current quarter are hidden.)  This may overlap with the epic for courses #11 , so coordinate with that team.)

* Each course links to a course show page, which for now is a placeholder.   Eventually, we had tutors on the top half, and tutor timeslots on the bottom half (creating this placeholder might be done by staff, or we might have the students do it.)

* Add to the top of each course show page a table of tutors for that courseThe tutor names are visible to public and guest, but to see tutor emails you have to login as a member.

* Add to the bottom of each course page a table of online office hours time slots.   All information is visible to public and guest except email and zoom link; those require logging in as a member.

* Modify the view on the home page so that it shows, for each course, the next three online office hours slots for that course (based on day of week and time of day).   Include any that are currently in progress.    Show courses, and tutor names, but do not show emails or zoom links unless use is logged in as a member.

**Comment by JacquelineMai** [comment]
* First 4 bullet points seem to be done (on prod heroku app)
* Final point not done- showing upcoming and current office hr slots
