### ISSUE TITLE
On the main page, make the current filtered quarter be in a more readable format

### ISSUE THREAD

**Issue by jayleenli** [ucsb-cs156-s21/proj-ucsb-cs-las#130]
# User Story

As a user I can see current course info on the main page so that I know about the current courses this quarter.

# Acceptance Criteria

- [x] Main page should not say "currently filtering by quarter 20211", it should say something like "currently filtering by quarter W21"
- [x] The values in the table for "quarter" on the page should also not be in numeric format (20211) and should be in a normal readable format (ex, W21)
![image](https://user-images.githubusercontent.com/25646026/109110998-c3e06a80-76fd-11eb-8df7-6c8dd9c84aca.png)

# Implementation Todos

Front end:

- [x] Main page front end is changed to show the quarter filter in a more readable output. (described above)
- [x] Main page table values show the quarter in a more readable output. (described above)

Back end:
- [x] Change the backend endpoint for the course table on the main page to return readable output format and not numeric form.

Testing:

- [x] All backend endpoints affected by the backend change still work as expected

Note: there are two ways this can be done-> mostly frontend changes only or mostly backend changes. I designed this issue to be mostly backend changes since that would be better practice but if that ends up breaking many things, look into the front end way.

**Comment by JacquelineMai** [comment]
Looks like this was completed in a different PR than the one linked
