### ISSUE TITLE
F20-6pm-c CRUD for tutor, tutor assignment, online office hours

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-s21/proj-ucsb-cs-las#14]
The theme of this epic is adding features to maintain tutors, tutor assignments, and online office hours.

The tutor table has fields for "tutor id", fname, lname, email.

 The tutor assignment table has fields for "tutor id", "course id", "assignment type" (where assignment type is "LA", "190J", "TA").  LA is paid LA, TA is graduate TA, and 190J is "LA in training, taking CMPSC 190J".

 The online office hours table has fields for "tutor assignment id",  "day of week", "start time", "end time", "zoom room link", "notes".

* CRUD operations for tutors  (accessible to instructor/admin).  
  - Instructors have edit/delete access to all entries for their course, and view access to all entries for all courses.
  - Admins have view/edit/delete access to all entries 
  - Members have view only access to all entries
  - Guests have no access to entries in this table.

* CRUD operations for tutor assignments  (accessible to instructor/admin).  
  - Instructors have edit/delete access to all entries for their course, and view access to all entries for all courses.
  - Admins have view/edit/delete access to all entries 
  - Members have view only access to all entries
  - Guests have no access to entries in this table.

* CRUD operations for online office hours (accessible to tutor/instructor/admin).  
  - Note that a tutor should only have edit/delete access to their OWN entries in this table, and view access to all other entries for all courses.
  - Instructors have edit/delete access to all entries for their course, and view access to all entries for all courses.
  - Admins have view/edit/delete access to all entries 
  - Members have view only access to all entries
  - Guests have no access to entries in this table.

**Comment by JacquelineMai** [comment]
* When logged in as an instructor, CRUD operations seem to be broken on heroku prod

**Comment by jayleenli** [comment]
Related to #83

**Comment by pconrad** [comment]
Already addressed in later issues
