### ISSUE TITLE
Fix footer CSS

### ISSUE THREAD

**Issue by jayleenli** [ucsb-cs156-s21/proj-ucsb-cs-las#142]
# Bug Report

Footer touches the table on some pages and table seems close to being cut off from the footer.    Plus, the footer scrolls along with the table contents, and obscures a few rows of the table.

![proj-ucsb-cs-las-footer-bug](https://user-images.githubusercontent.com/1119017/117857960-39aa9b80-b242-11eb-9db5-a7d53d32eee9.gif)

# Steps to Reproduce

There are many ways, but one way is to go to /admin/viewLogins and scroll to the bottom.   

# Expected / Desired Behavior

We want the footer to stay put at the bottom of the page; either it should 
* (a) show up after the table is done, and not be visible until you scroll to the bottom, *OR*
* (b) or it should stay put at the bottom of the web page window, and the table should scroll in a window in between.

# Observed / Actual Behavior

The footer scrolls with the page content, and interrupts the page content as shown in the linked screenshot animation above.

# Discussion

> ⚠️ Do not follow the below PRs! They are hacky workarounds that do not solve the core issue! See the comment below by @btk5h for details.

~~This issue has already been solved in mapache search, you can use as reference: https://github.com/ucsb-cs156-w21/proj-mapache-search/pull/182/files~~

~~This PR may also be relevant: https://github.com/ucsb-cs156-s21/proj-ucsb-courses-search/pull/212~~

**Comment by pconrad** [comment]
We should try to fix this behavior as part of this issue, if it's related.  If not, we should file it as a separate bug.

![image](https://user-images.githubusercontent.com/1119017/112026849-d8910200-8af3-11eb-9bb4-1ee10b711969.png)

**Comment by btk5h** [comment]
Do not follow the PRs referenced in the issue description. The fundamental issue is that absolute positioning is an absolute mess and 99% of the time should not be used for layout. If you remove the following lines:

https://github.com/ucsb-cs156-s21/proj-ucsb-cs-las/blob/221ec4aec860f30eeb0d8c285bcb0fd35926fc42/javascript/src/main/App.css#L57-L69

The footer will then be properly included in the page layout.

**Comment by PureDreamerGk** [comment]
I am wondering whether this is still a issue because there seems to have a solution for fix the footer.

**Comment by btk5h** [comment]
@PureDreamerGk Yes, this is still an issue, please try replicating the bug as @pconrad described above. The solution should NOT use absolute positioning.

**Comment by PureDreamerGk** [comment]
I choose for the desired behavior, which means that the footer will not show until you scroll to the button
<img width="1428" alt="Screen Shot 2021-05-27 at 2 49 40 PM" src="https://user-images.githubusercontent.com/34769184/119901449-c8820e00-befa-11eb-9d45-9933bea9b6ab.png">
This is what it shows on the local branch, I am wondering whether it achieves the goal of fixing the problem.
Another question is that for the issue, the only file I should edit would be App.css, correct.

**Comment by btk5h** [comment]
@PureDreamerGk It might not occur on the page you tested, but I believe I replicated it on the qa site on the admins page.

I've also only done basic in-browser prototyping to give hints on this issue, you may find that you need to change more or fewer things than what I suggested.
