### ISSUE TITLE
Make Office Hours Table Component Sortable by Column

### ISSUE THREAD

**Issue by WadeVaresio** [ucsb-cs156-s21/proj-ucsb-cs-las#180]
# User Story

As a user I can sort each column in the Office Hours table on the Office Hours Page so that I can easily sort tutors by certain criteria

# Discussion 

The OfficeHours table is implemented by the component:

* <https://github.com/ucsb-cs156-s21/proj-ucsb-cs-las/blob/main/javascript/src/main/components/OfficeHours/OfficeHourTable.js>

You'll find this code: 

```js
const columns = [{
        dataField: 'id',
        text: 'id'
    }, {
        dataField: 'startTime',
        text: 'Start Time'
    }, {
        dataField: 'endTime',
        text: 'End Time'
    }, {
        dataField: 'dayOfWeek',
        text: 'Day'
```
etc...

If you add this to each of the objects:

```
 sort: true,
```

Then the table becomes sortable.  Like this:

```js
const columns = [{
        dataField: 'id',
        text: 'id',
        sort: true
    }, {
        dataField: 'startTime',
        text: 'Start Time',
         sort: true
    }, {
        dataField: 'endTime',
        text: 'End Time',
         sort: true
    }, {
```
etc.

You should also find this line of code:

```
 <BootstrapTable keyField='id' data={officeHours} columns={columns} striped />
```

and change it to:

```
 <BootstrapTable 
    bootstrap4=true,
    keyField='id' 
    data={officeHours} 
    columns={columns} 
    striped 
  />
```
 
Note that at first, you won't see any indication that the table is sortable, i.e. you won't see little `^` or `v` symbols in the headers.  But if you click on them, they will sort.

The caret will show up after the CSS changes in issue #181 are merged.

# Acceptance Criteria

- [x] Each column in the Office Hours table is sortable.
- [x] Each column correctly sorts in ascending order
- [x] Each column correctly sorts in descending order

Testing:
- [x] Verify via inspection whether each column correctly sorts.

**Comment by danmolloy** [comment]
Hi, can I please take on this issue?
