### ISSUE TITLE
Add new image for brand logo

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-s21/proj-ucsb-cs-las#184]
# User Story

As a user I can see a cute brand icon so that I can feel awesome about the app.

# Discussion 

If you look at proj-ucsb-courses-search, and this <https://github.com/ucsb-cs156-s21/proj-ucsb-courses-search/pull/227>, you'll see that there is a cute logo in the "brand" spot.

In this issue, you'll add something similar for ucsb-cs-las.

We'll provide you with a link to the logo, and you'll make the changes so that it appears in the much thicker navbar (fixing the appearance of that is a separate story.)

Here is the new brand logo: 
![logo-ucsb-courses-search](https://user-images.githubusercontent.com/27262771/117902816-28ce4a00-b283-11eb-9ffc-35f0bae82651.png)

Note that the other PR was done incorrectly... the link should be a absolute link, not a relative one, so that the image still shows up when you navigate to other pages.

# Acceptance Criteria

- [x] The logo should show up in the navbar on the home page
- [x] The logo should show up in the navbar on all pages

**Comment by WadeVaresio** [comment]
Closing as PR #213 addresses this issue.
