### ISSUE TITLE
Use Bootstrap classes to replace hardcoded CSS in tutor assignment and header components

### ISSUE THREAD

**Issue by rowantran** [ucsb-cs156-s21/proj-ucsb-cs-las#229]
## User Story
As a user I can see more space between the "New Tutor Assignment" Button and the Tutors table on the Courses page so that it is easier to distinguish between components.
As an admin I can read a description of the meaning behind the login page so that I understand the data displayed to me.
As a developer I can use the Bootstrap classes for styling, rather than relying on manual CSS.

See #189 and #190, and associated PRs, for the code this story is cleaning up.

## Discussion
Both of the above linked issues were completed successfully, but using a CSS object embedded directly into the JSX. We want to use Bootstrap classes instead to have a more maintainable and less "hard-coded" solution.

## Acceptance Criteria
- [x] There should be noticeable space between the "New Tutor Assignment" button and the Tutors table.
- [x] There is a suitable description of the pages functionality visible to the admin.
- [x] Bootstrap classes are being used where appropriate to provide styling.

## Implementation Todos
Frontend:
- [x] Replace the hardcoded CSS in the `TutorAssignments` page.
- [x] Replace the hardcoded CSS in the `ViewLogins` page.

Tests:
- [x] All tests still pass
- [x] Affected pages look good from interactive testing

**Comment by phtcon** [comment]
I was asked about testing for this one.

Techincally you could write  a test to check for the presence of description text.   But that's really just writing the code twice.  I think this is a story where the testing is more likely to be just "deploy it... and does it look ok"?

When it gets code with lots logic and multiple cases, and interactions with db and apis, we'll be much more interested in good test coverage.
