### ISSUE TITLE
Create a frontend page to display Room Slot Entries

### ISSUE THREAD

**Issue by RaghubirChimni** [ucsb-cs156-s21/proj-ucsb-cs-las#244]
# User Story

As a user I can view the current time slots associated with physical rooms, so that we can keep track of which rooms are being used at which times and associate office hours with these slots (see #245).

# Acceptance Criteria
- [x] The navbar allows us to navigate to the Room Slots page.
- [x] There is a table showing information on all current Room Slots.

# Implementation Todos

Front end:
- [x] Add a route to the new page
- [x] Add Room Slots to navbar
- [x] Add a page component for Room Slots
- [x] Add a table on the Room Slots page to display current room slot entries
- [x] Add all necessary API calls to connect page to backend

Back end:
- No additional backend functionality is required for this story specifically (CRUD endpoints are being implemented in a different story)

Testing:
- [x] Front end tests pass and there is adequate coverage

**Comment by rowantran** [comment]
note: let's ask staff about what roles we want to have access to (a) view room slots and (b) edit them

**Comment by rowantran** [comment]
q: do we need an edit functionality at all? office hours doesn't have this

**Comment by rowantran** [comment]
This story is done, but waiting to finish #248 to make a combined PR for both stories since neither story is very useful without the other being completed.
