### ISSUE TITLE
Add CSV upload for course information (on Admin's page for maintaining courses.) (4 points)

### ISSUE THREAD

**Issue by alejandrodiera** [ucsb-cs156-s21/proj-ucsb-cs-las#42]
# User Story

As an admin, I can provide a comma-separated values file so that I can maintain or modify information for courses. 

# Acceptance Criteria

- [ ] Admins will be able to see an upload section on the Admin's page that takes a CSV file.
- [ ] Admins will see an indicator (timestamp, comment, etc.) informing when the previous file was uploaded. 
...

# Implementation Todos

Front end:

- [ ] Add a file upload button only on the "Admin" page.
- [ ] Add one of the previously listed indicators underneath the file upload button on the "Admin" page.
- upload -> converts csv to course list -> empties the original table -> adds every course from course list to course table
...

Back end:

- [ ] Reads input lines from the CSV files and output it with the same format that is displayed on the course search.
- [ ] For timestamp route, create or use a Java integrated library that gets real time.
...

Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage
...

**Comment by JacquelineMai** [comment]
A variation of this feature was added with #162, where the CSV upload/download field is on the courses page itself
