### ISSUE TITLE
As an instructor or Admin, I can delete tutor assignments so that admins and instructors can delete entries to the tutor assignment list

### ISSUE THREAD

**Issue by gmundewadi** [ucsb-cs156-s21/proj-ucsb-cs-las#47]
As an admin I can delete tutor assignments so that tutor assignments are accurate.

# Discussion
Currently there is a delete button on the Tutor Asssignments page, however it does not work.

# Acceptance Criteria

- [x] tutor assignment deleted from tutor list
- [x] a button to delete tutor assignments
- [x] only instructor and admins can delete new tutors

# Implementation Todos

Front end:

- for hint on implementation see how adding course was implemented https://github.com/ucsb-cs156-f20/proj-ucsb-cs-las/pull/4

- [x] add delete button to tutor assignment page
- [x] when I click delete I am sent back to the tutor assignment list and the tutor assignment should be removed.

Back end:

- [x] add a tutor assignment controller with route for deleting tutor assignments (similar to course controller)
- [x] Pass data to our frontend

Testing:

- [x] Front end tests pass and there is adequate coverage
- [x] Back end tests pass and there is adequate coverage

**Comment by JacquelineMai** [comment]
There is a delete button in the Tutor Assignment table, but it doesn't currently work
