### ISSUE TITLE
Form Validation for Submitting Tutor Assignments and Tutor Office Hours

### ISSUE THREAD

**Issue by jayleenli** [ucsb-cs156-s21/proj-ucsb-cs-las#83]
# User Story

As a tutor I can see what went wrong when I try to submit assignments/hours so that I understand why I formatted something incorrectly.

# Acceptance Criteria

- [ ] Error messages are not general i.e "please input a valid time" or "please input a valid zoom link"
![image](https://user-images.githubusercontent.com/25646026/104962027-69305200-598c-11eb-9388-59f2badc0046.png)

# Implementation Todos

Front end:

- [ ] Be able to display error messages from the backend so users can see it and understand what part of their input is formatted incorrectly
...

Back end:

- [ ] Have better returned messages when there is an error 
...

Testing:

- [ ] Create tests for success and error cases for API/CRUD calls
...

**Comment by JacquelineMai** [comment]
Office hr validation seems to be covered by these PRs: #140, #143 
I didn't see any PRs from last quarter directly pertaining to tutor assignment validation, but there is field validation on that page
